/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://www.karmickonnexions.com',
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
      { userAgent: '*', allow: '/' },
      { userAgent: '*', disallow: '/studio' },
    ],
  },
  exclude: ['/studio', '/studio/*', '/api/*'],
  changefreq: 'weekly',
  priority: 0.7,
  sitemapSize: 7000,
  additionalPaths: async (config) => [
    await config.transform(config, '/'),
    await config.transform(config, '/about'),
    await config.transform(config, '/services/bpo-outsourcing'),
    await config.transform(config, '/services/bpo-outsourcing/hr-outsourcing'),
    await config.transform(config, '/services/bpo-outsourcing/finance-accounts'),
    await config.transform(config, '/services/bpo-outsourcing/crm-sales-ops'),
    await config.transform(config, '/services/bpo-outsourcing/marketing-services'),
    await config.transform(config, '/services/elearning'),
    await config.transform(config, '/services/elearning/lms-platform'),
    await config.transform(config, '/services/elearning/training-programs'),
    await config.transform(config, '/services/elearning/career-guidance'),
    await config.transform(config, '/services/global-workforce'),
    await config.transform(config, '/services/global-workforce/talent-acquisition'),
    await config.transform(config, '/services/global-workforce/contract-staffing'),
    await config.transform(config, '/services/global-workforce/rpo'),
    await config.transform(config, '/services/corporate-apparel'),
    await config.transform(config, '/services/ai-automation'),
    await config.transform(config, '/programs'),
    await config.transform(config, '/programs/business-stack'),
    await config.transform(config, '/programs/data-zenmaster'),
    await config.transform(config, '/programs/gen-ai'),
    await config.transform(config, '/industries'),
    await config.transform(config, '/why-karmic'),
    await config.transform(config, '/case-studies'),
    await config.transform(config, '/blog'),
    await config.transform(config, '/careers'),
    await config.transform(config, '/contact'),
    await config.transform(config, '/get-proposal'),
    await config.transform(config, '/initiatives'),
    await config.transform(config, '/initiatives/swabhimaan'),
  ],
}
